### ISSUE TITLE
Shift from 'async' to 'non_blocking' in cuda

### ISSUE THREAD

**Issue by cclauss** [facebookresearch/adversarial_image_defenses#14]
__async__ is a reserved word in Python 3.7 so cuda is deprecating the function parameter __async__ in favor of __non_blocking__.

https://github.com/pytorch/pytorch/blob/4d28b65fb8978f1c34765d56f18c07042e70a43a/torch/_utils.py#L20-L21

[flake8](http://flake8.pycqa.org) testing of https://github.com/facebookresearch/adversarial_image_defenses on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./adversarial/lib/adversary.py:64:34: E999 SyntaxError: invalid syntax
        target = target.cuda(async=True)
                                 ^
./adversarial/lib/convnet.py:63:44: E999 SyntaxError: invalid syntax
                targets = targets.cuda(async=True)
                                           ^
2     E999 SyntaxError: invalid syntax
2
```

**Comment by lvdmaaten** [comment]
Thanks for reporting this, @cclauss.

There have been many breaking changes in PyTorch since we released this code; this is only one of them. Because we are not developing this codebase further and are merely are providing it for our results to be reproducible, we do not plan to implement changes that are needed to make this code work on newer PyTorch versions. The code should work fine on Python 2.7 and PyTorch v0.2.0 though -- please let us know if you have any issues there.

**Comment by cclauss** [comment]
No issues.  Thanks.  Closing.
