### ISSUE TITLE
Modifications to C&W Attack

### ISSUE THREAD

**Issue by ysharma1126** [facebookresearch/adversarial_image_defenses#5]
It is stated that: the attack has been 'modified with TV minimization, random cropping, and random pixel dropping'. What does this mean? No description was given on this in the paper. With what hyperparameter setting can all modifications be turned off?

Furthermore, with the modifications turned off, is the implementation here equivalent to Carlini's original formulation? Doesn't seem to be the case, for one, the 'binary_search_steps' hyperparameter is missing. If it isn't, can you please explain what the formulation is here? Also, can a formulation equivalent to the original C&W attack be added to the repository? The original formulation has been validated to be a very successful attack, so I feel it, without modification, should be included in this repository. 

A Tensorflow implemenation of the C&W L2 attack is provided in the 'carlini/nn_robust_attacks' repository and in Tensorflow's Cleverhans repository.

**Comment by lvdmaaten** [comment]
If you set, for instance, `tv_weight` to a value `> 0.`, you will run a version of the C&W attack that aims to attack a model that uses a TVM defense. If you use the default input arguments, it should implement the standard C&W attack. We re-implemented the C&W attack because we do not want to introduce TensorFlow dependencies.

We are providing this code as-is so that people can reproduce the results reported in our paper; we have no intention of turning it into a more general-purpose library like cleverhans.

General remark: Please use this forum for posting issues, not for posting questions that can be answered by a relatively [quick read of the code](https://github.com/facebookresearch/adversarial_image_defenses/blob/84e47bce290d4f4eb0d24e92ea77f1bc9357becd/adversarial/lib/adversary.py#L365-L372); this is not StackOverflow / Quora / Reddit. If there are features that you think really need to be added in our code, we are happy to accept pull requests.

**Comment by ysharma1126** [comment]
I asked these questions here because Mayank suggested I ask the questions here, I won't ask such questions here again.
